/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as OffresOfferIdRouteImport } from './routes/offres.$offerId'
import { Route as EntreprisesCompanyIdRouteImport } from './routes/entreprises.$companyId'
import { Route as AuthenticatedRecruteurRouteImport } from './routes/_authenticated/recruteur'
import { Route as AuthenticatedCandidatRouteImport } from './routes/_authenticated/candidat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRecruteurIndexRouteImport } from './routes/_authenticated/recruteur.index'
import { Route as AuthenticatedCandidatIndexRouteImport } from './routes/_authenticated/candidat.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedRecruteurOffresRouteImport } from './routes/_authenticated/recruteur.offres'
import { Route as AuthenticatedRecruteurMessagesRouteImport } from './routes/_authenticated/recruteur.messages'
import { Route as AuthenticatedRecruteurFavorisRouteImport } from './routes/_authenticated/recruteur.favoris'
import { Route as AuthenticatedRecruteurEntrepriseRouteImport } from './routes/_authenticated/recruteur.entreprise'
import { Route as AuthenticatedRecruteurCvthequeRouteImport } from './routes/_authenticated/recruteur.cvtheque'
import { Route as AuthenticatedRecruteurCandidaturesRouteImport } from './routes/_authenticated/recruteur.candidatures'
import { Route as AuthenticatedCandidatProfilRouteImport } from './routes/_authenticated/candidat.profil'
import { Route as AuthenticatedCandidatMessagesRouteImport } from './routes/_authenticated/candidat.messages'
import { Route as AuthenticatedCandidatCvRouteImport } from './routes/_authenticated/candidat.cv'
import { Route as AuthenticatedCandidatCandidaturesRouteImport } from './routes/_authenticated/candidat.candidatures'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as AuthenticatedAdminReferentielsRouteImport } from './routes/_authenticated/admin.referentiels'
import { Route as AuthenticatedAdminOffresRouteImport } from './routes/_authenticated/admin.offres'
import { Route as AuthenticatedAdminEntreprisesRouteImport } from './routes/_authenticated/admin.entreprises'
import { Route as AuthenticatedRecruteurOffresNouvelleRouteImport } from './routes/_authenticated/recruteur.offres.nouvelle'
import { Route as AuthenticatedRecruteurOffresOfferIdRouteImport } from './routes/_authenticated/recruteur.offres.$offerId'

const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresOfferIdRoute = OffresOfferIdRouteImport.update({
  id: '/$offerId',
  path: '/$offerId',
  getParentRoute: () => OffresRoute,
} as any)
const EntreprisesCompanyIdRoute = EntreprisesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => EntreprisesRoute,
} as any)
const AuthenticatedRecruteurRoute = AuthenticatedRecruteurRouteImport.update({
  id: '/recruteur',
  path: '/recruteur',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatRoute = AuthenticatedCandidatRouteImport.update({
  id: '/candidat',
  path: '/candidat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecruteurIndexRoute =
  AuthenticatedRecruteurIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedCandidatIndexRoute =
  AuthenticatedCandidatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidatRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedRecruteurOffresRoute =
  AuthenticatedRecruteurOffresRouteImport.update({
    id: '/offres',
    path: '/offres',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedRecruteurMessagesRoute =
  AuthenticatedRecruteurMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedRecruteurFavorisRoute =
  AuthenticatedRecruteurFavorisRouteImport.update({
    id: '/favoris',
    path: '/favoris',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedRecruteurEntrepriseRoute =
  AuthenticatedRecruteurEntrepriseRouteImport.update({
    id: '/entreprise',
    path: '/entreprise',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedRecruteurCvthequeRoute =
  AuthenticatedRecruteurCvthequeRouteImport.update({
    id: '/cvtheque',
    path: '/cvtheque',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedRecruteurCandidaturesRoute =
  AuthenticatedRecruteurCandidaturesRouteImport.update({
    id: '/candidatures',
    path: '/candidatures',
    getParentRoute: () => AuthenticatedRecruteurRoute,
  } as any)
const AuthenticatedCandidatProfilRoute =
  AuthenticatedCandidatProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedCandidatRoute,
  } as any)
const AuthenticatedCandidatMessagesRoute =
  AuthenticatedCandidatMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedCandidatRoute,
  } as any)
const AuthenticatedCandidatCvRoute = AuthenticatedCandidatCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedCandidatRoute,
} as any)
const AuthenticatedCandidatCandidaturesRoute =
  AuthenticatedCandidatCandidaturesRouteImport.update({
    id: '/candidatures',
    path: '/candidatures',
    getParentRoute: () => AuthenticatedCandidatRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferentielsRoute =
  AuthenticatedAdminReferentielsRouteImport.update({
    id: '/referentiels',
    path: '/referentiels',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffresRoute =
  AuthenticatedAdminOffresRouteImport.update({
    id: '/offres',
    path: '/offres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntreprisesRoute =
  AuthenticatedAdminEntreprisesRouteImport.update({
    id: '/entreprises',
    path: '/entreprises',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedRecruteurOffresNouvelleRoute =
  AuthenticatedRecruteurOffresNouvelleRouteImport.update({
    id: '/nouvelle',
    path: '/nouvelle',
    getParentRoute: () => AuthenticatedRecruteurOffresRoute,
  } as any)
const AuthenticatedRecruteurOffresOfferIdRoute =
  AuthenticatedRecruteurOffresOfferIdRouteImport.update({
    id: '/$offerId',
    path: '/$offerId',
    getParentRoute: () => AuthenticatedRecruteurOffresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRouteWithChildren
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/offres': typeof OffresRouteWithChildren
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/candidat': typeof AuthenticatedCandidatRouteWithChildren
  '/recruteur': typeof AuthenticatedRecruteurRouteWithChildren
  '/entreprises/$companyId': typeof EntreprisesCompanyIdRoute
  '/offres/$offerId': typeof OffresOfferIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/admin/entreprises': typeof AuthenticatedAdminEntreprisesRoute
  '/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/admin/referentiels': typeof AuthenticatedAdminReferentielsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/candidat/candidatures': typeof AuthenticatedCandidatCandidaturesRoute
  '/candidat/cv': typeof AuthenticatedCandidatCvRoute
  '/candidat/messages': typeof AuthenticatedCandidatMessagesRoute
  '/candidat/profil': typeof AuthenticatedCandidatProfilRoute
  '/recruteur/candidatures': typeof AuthenticatedRecruteurCandidaturesRoute
  '/recruteur/cvtheque': typeof AuthenticatedRecruteurCvthequeRoute
  '/recruteur/entreprise': typeof AuthenticatedRecruteurEntrepriseRoute
  '/recruteur/favoris': typeof AuthenticatedRecruteurFavorisRoute
  '/recruteur/messages': typeof AuthenticatedRecruteurMessagesRoute
  '/recruteur/offres': typeof AuthenticatedRecruteurOffresRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/candidat/': typeof AuthenticatedCandidatIndexRoute
  '/recruteur/': typeof AuthenticatedRecruteurIndexRoute
  '/recruteur/offres/$offerId': typeof AuthenticatedRecruteurOffresOfferIdRoute
  '/recruteur/offres/nouvelle': typeof AuthenticatedRecruteurOffresNouvelleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRouteWithChildren
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/offres': typeof OffresRouteWithChildren
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/entreprises/$companyId': typeof EntreprisesCompanyIdRoute
  '/offres/$offerId': typeof OffresOfferIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/admin/entreprises': typeof AuthenticatedAdminEntreprisesRoute
  '/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/admin/referentiels': typeof AuthenticatedAdminReferentielsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/candidat/candidatures': typeof AuthenticatedCandidatCandidaturesRoute
  '/candidat/cv': typeof AuthenticatedCandidatCvRoute
  '/candidat/messages': typeof AuthenticatedCandidatMessagesRoute
  '/candidat/profil': typeof AuthenticatedCandidatProfilRoute
  '/recruteur/candidatures': typeof AuthenticatedRecruteurCandidaturesRoute
  '/recruteur/cvtheque': typeof AuthenticatedRecruteurCvthequeRoute
  '/recruteur/entreprise': typeof AuthenticatedRecruteurEntrepriseRoute
  '/recruteur/favoris': typeof AuthenticatedRecruteurFavorisRoute
  '/recruteur/messages': typeof AuthenticatedRecruteurMessagesRoute
  '/recruteur/offres': typeof AuthenticatedRecruteurOffresRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/candidat': typeof AuthenticatedCandidatIndexRoute
  '/recruteur': typeof AuthenticatedRecruteurIndexRoute
  '/recruteur/offres/$offerId': typeof AuthenticatedRecruteurOffresOfferIdRoute
  '/recruteur/offres/nouvelle': typeof AuthenticatedRecruteurOffresNouvelleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRouteWithChildren
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/offres': typeof OffresRouteWithChildren
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/candidat': typeof AuthenticatedCandidatRouteWithChildren
  '/_authenticated/recruteur': typeof AuthenticatedRecruteurRouteWithChildren
  '/entreprises/$companyId': typeof EntreprisesCompanyIdRoute
  '/offres/$offerId': typeof OffresOfferIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/_authenticated/admin/entreprises': typeof AuthenticatedAdminEntreprisesRoute
  '/_authenticated/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/_authenticated/admin/referentiels': typeof AuthenticatedAdminReferentielsRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/candidat/candidatures': typeof AuthenticatedCandidatCandidaturesRoute
  '/_authenticated/candidat/cv': typeof AuthenticatedCandidatCvRoute
  '/_authenticated/candidat/messages': typeof AuthenticatedCandidatMessagesRoute
  '/_authenticated/candidat/profil': typeof AuthenticatedCandidatProfilRoute
  '/_authenticated/recruteur/candidatures': typeof AuthenticatedRecruteurCandidaturesRoute
  '/_authenticated/recruteur/cvtheque': typeof AuthenticatedRecruteurCvthequeRoute
  '/_authenticated/recruteur/entreprise': typeof AuthenticatedRecruteurEntrepriseRoute
  '/_authenticated/recruteur/favoris': typeof AuthenticatedRecruteurFavorisRoute
  '/_authenticated/recruteur/messages': typeof AuthenticatedRecruteurMessagesRoute
  '/_authenticated/recruteur/offres': typeof AuthenticatedRecruteurOffresRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/candidat/': typeof AuthenticatedCandidatIndexRoute
  '/_authenticated/recruteur/': typeof AuthenticatedRecruteurIndexRoute
  '/_authenticated/recruteur/offres/$offerId': typeof AuthenticatedRecruteurOffresOfferIdRoute
  '/_authenticated/recruteur/offres/nouvelle': typeof AuthenticatedRecruteurOffresNouvelleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/entreprises'
    | '/faq'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/offres'
    | '/reinitialiser-mot-de-passe'
    | '/admin'
    | '/candidat'
    | '/recruteur'
    | '/entreprises/$companyId'
    | '/offres/$offerId'
    | '/services/$serviceId'
    | '/admin/entreprises'
    | '/admin/offres'
    | '/admin/referentiels'
    | '/admin/utilisateurs'
    | '/candidat/candidatures'
    | '/candidat/cv'
    | '/candidat/messages'
    | '/candidat/profil'
    | '/recruteur/candidatures'
    | '/recruteur/cvtheque'
    | '/recruteur/entreprise'
    | '/recruteur/favoris'
    | '/recruteur/messages'
    | '/recruteur/offres'
    | '/admin/'
    | '/candidat/'
    | '/recruteur/'
    | '/recruteur/offres/$offerId'
    | '/recruteur/offres/nouvelle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/entreprises'
    | '/faq'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/offres'
    | '/reinitialiser-mot-de-passe'
    | '/entreprises/$companyId'
    | '/offres/$offerId'
    | '/services/$serviceId'
    | '/admin/entreprises'
    | '/admin/offres'
    | '/admin/referentiels'
    | '/admin/utilisateurs'
    | '/candidat/candidatures'
    | '/candidat/cv'
    | '/candidat/messages'
    | '/candidat/profil'
    | '/recruteur/candidatures'
    | '/recruteur/cvtheque'
    | '/recruteur/entreprise'
    | '/recruteur/favoris'
    | '/recruteur/messages'
    | '/recruteur/offres'
    | '/admin'
    | '/candidat'
    | '/recruteur'
    | '/recruteur/offres/$offerId'
    | '/recruteur/offres/nouvelle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/entreprises'
    | '/faq'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/offres'
    | '/reinitialiser-mot-de-passe'
    | '/_authenticated/admin'
    | '/_authenticated/candidat'
    | '/_authenticated/recruteur'
    | '/entreprises/$companyId'
    | '/offres/$offerId'
    | '/services/$serviceId'
    | '/_authenticated/admin/entreprises'
    | '/_authenticated/admin/offres'
    | '/_authenticated/admin/referentiels'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/candidat/candidatures'
    | '/_authenticated/candidat/cv'
    | '/_authenticated/candidat/messages'
    | '/_authenticated/candidat/profil'
    | '/_authenticated/recruteur/candidatures'
    | '/_authenticated/recruteur/cvtheque'
    | '/_authenticated/recruteur/entreprise'
    | '/_authenticated/recruteur/favoris'
    | '/_authenticated/recruteur/messages'
    | '/_authenticated/recruteur/offres'
    | '/_authenticated/admin/'
    | '/_authenticated/candidat/'
    | '/_authenticated/recruteur/'
    | '/_authenticated/recruteur/offres/$offerId'
    | '/_authenticated/recruteur/offres/nouvelle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AProposRoute: typeof AProposRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  EntreprisesRoute: typeof EntreprisesRouteWithChildren
  FaqRoute: typeof FaqRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  OffresRoute: typeof OffresRouteWithChildren
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$offerId': {
      id: '/offres/$offerId'
      path: '/$offerId'
      fullPath: '/offres/$offerId'
      preLoaderRoute: typeof OffresOfferIdRouteImport
      parentRoute: typeof OffresRoute
    }
    '/entreprises/$companyId': {
      id: '/entreprises/$companyId'
      path: '/$companyId'
      fullPath: '/entreprises/$companyId'
      preLoaderRoute: typeof EntreprisesCompanyIdRouteImport
      parentRoute: typeof EntreprisesRoute
    }
    '/_authenticated/recruteur': {
      id: '/_authenticated/recruteur'
      path: '/recruteur'
      fullPath: '/recruteur'
      preLoaderRoute: typeof AuthenticatedRecruteurRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidat': {
      id: '/_authenticated/candidat'
      path: '/candidat'
      fullPath: '/candidat'
      preLoaderRoute: typeof AuthenticatedCandidatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recruteur/': {
      id: '/_authenticated/recruteur/'
      path: '/'
      fullPath: '/recruteur/'
      preLoaderRoute: typeof AuthenticatedRecruteurIndexRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/candidat/': {
      id: '/_authenticated/candidat/'
      path: '/'
      fullPath: '/candidat/'
      preLoaderRoute: typeof AuthenticatedCandidatIndexRouteImport
      parentRoute: typeof AuthenticatedCandidatRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/recruteur/offres': {
      id: '/_authenticated/recruteur/offres'
      path: '/offres'
      fullPath: '/recruteur/offres'
      preLoaderRoute: typeof AuthenticatedRecruteurOffresRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/recruteur/messages': {
      id: '/_authenticated/recruteur/messages'
      path: '/messages'
      fullPath: '/recruteur/messages'
      preLoaderRoute: typeof AuthenticatedRecruteurMessagesRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/recruteur/favoris': {
      id: '/_authenticated/recruteur/favoris'
      path: '/favoris'
      fullPath: '/recruteur/favoris'
      preLoaderRoute: typeof AuthenticatedRecruteurFavorisRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/recruteur/entreprise': {
      id: '/_authenticated/recruteur/entreprise'
      path: '/entreprise'
      fullPath: '/recruteur/entreprise'
      preLoaderRoute: typeof AuthenticatedRecruteurEntrepriseRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/recruteur/cvtheque': {
      id: '/_authenticated/recruteur/cvtheque'
      path: '/cvtheque'
      fullPath: '/recruteur/cvtheque'
      preLoaderRoute: typeof AuthenticatedRecruteurCvthequeRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/recruteur/candidatures': {
      id: '/_authenticated/recruteur/candidatures'
      path: '/candidatures'
      fullPath: '/recruteur/candidatures'
      preLoaderRoute: typeof AuthenticatedRecruteurCandidaturesRouteImport
      parentRoute: typeof AuthenticatedRecruteurRoute
    }
    '/_authenticated/candidat/profil': {
      id: '/_authenticated/candidat/profil'
      path: '/profil'
      fullPath: '/candidat/profil'
      preLoaderRoute: typeof AuthenticatedCandidatProfilRouteImport
      parentRoute: typeof AuthenticatedCandidatRoute
    }
    '/_authenticated/candidat/messages': {
      id: '/_authenticated/candidat/messages'
      path: '/messages'
      fullPath: '/candidat/messages'
      preLoaderRoute: typeof AuthenticatedCandidatMessagesRouteImport
      parentRoute: typeof AuthenticatedCandidatRoute
    }
    '/_authenticated/candidat/cv': {
      id: '/_authenticated/candidat/cv'
      path: '/cv'
      fullPath: '/candidat/cv'
      preLoaderRoute: typeof AuthenticatedCandidatCvRouteImport
      parentRoute: typeof AuthenticatedCandidatRoute
    }
    '/_authenticated/candidat/candidatures': {
      id: '/_authenticated/candidat/candidatures'
      path: '/candidatures'
      fullPath: '/candidat/candidatures'
      preLoaderRoute: typeof AuthenticatedCandidatCandidaturesRouteImport
      parentRoute: typeof AuthenticatedCandidatRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/referentiels': {
      id: '/_authenticated/admin/referentiels'
      path: '/referentiels'
      fullPath: '/admin/referentiels'
      preLoaderRoute: typeof AuthenticatedAdminReferentielsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offres': {
      id: '/_authenticated/admin/offres'
      path: '/offres'
      fullPath: '/admin/offres'
      preLoaderRoute: typeof AuthenticatedAdminOffresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entreprises': {
      id: '/_authenticated/admin/entreprises'
      path: '/entreprises'
      fullPath: '/admin/entreprises'
      preLoaderRoute: typeof AuthenticatedAdminEntreprisesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/recruteur/offres/nouvelle': {
      id: '/_authenticated/recruteur/offres/nouvelle'
      path: '/nouvelle'
      fullPath: '/recruteur/offres/nouvelle'
      preLoaderRoute: typeof AuthenticatedRecruteurOffresNouvelleRouteImport
      parentRoute: typeof AuthenticatedRecruteurOffresRoute
    }
    '/_authenticated/recruteur/offres/$offerId': {
      id: '/_authenticated/recruteur/offres/$offerId'
      path: '/$offerId'
      fullPath: '/recruteur/offres/$offerId'
      preLoaderRoute: typeof AuthenticatedRecruteurOffresOfferIdRouteImport
      parentRoute: typeof AuthenticatedRecruteurOffresRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEntreprisesRoute: typeof AuthenticatedAdminEntreprisesRoute
  AuthenticatedAdminOffresRoute: typeof AuthenticatedAdminOffresRoute
  AuthenticatedAdminReferentielsRoute: typeof AuthenticatedAdminReferentielsRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEntreprisesRoute: AuthenticatedAdminEntreprisesRoute,
  AuthenticatedAdminOffresRoute: AuthenticatedAdminOffresRoute,
  AuthenticatedAdminReferentielsRoute: AuthenticatedAdminReferentielsRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCandidatRouteChildren {
  AuthenticatedCandidatCandidaturesRoute: typeof AuthenticatedCandidatCandidaturesRoute
  AuthenticatedCandidatCvRoute: typeof AuthenticatedCandidatCvRoute
  AuthenticatedCandidatMessagesRoute: typeof AuthenticatedCandidatMessagesRoute
  AuthenticatedCandidatProfilRoute: typeof AuthenticatedCandidatProfilRoute
  AuthenticatedCandidatIndexRoute: typeof AuthenticatedCandidatIndexRoute
}

const AuthenticatedCandidatRouteChildren: AuthenticatedCandidatRouteChildren = {
  AuthenticatedCandidatCandidaturesRoute:
    AuthenticatedCandidatCandidaturesRoute,
  AuthenticatedCandidatCvRoute: AuthenticatedCandidatCvRoute,
  AuthenticatedCandidatMessagesRoute: AuthenticatedCandidatMessagesRoute,
  AuthenticatedCandidatProfilRoute: AuthenticatedCandidatProfilRoute,
  AuthenticatedCandidatIndexRoute: AuthenticatedCandidatIndexRoute,
}

const AuthenticatedCandidatRouteWithChildren =
  AuthenticatedCandidatRoute._addFileChildren(
    AuthenticatedCandidatRouteChildren,
  )

interface AuthenticatedRecruteurOffresRouteChildren {
  AuthenticatedRecruteurOffresOfferIdRoute: typeof AuthenticatedRecruteurOffresOfferIdRoute
  AuthenticatedRecruteurOffresNouvelleRoute: typeof AuthenticatedRecruteurOffresNouvelleRoute
}

const AuthenticatedRecruteurOffresRouteChildren: AuthenticatedRecruteurOffresRouteChildren =
  {
    AuthenticatedRecruteurOffresOfferIdRoute:
      AuthenticatedRecruteurOffresOfferIdRoute,
    AuthenticatedRecruteurOffresNouvelleRoute:
      AuthenticatedRecruteurOffresNouvelleRoute,
  }

const AuthenticatedRecruteurOffresRouteWithChildren =
  AuthenticatedRecruteurOffresRoute._addFileChildren(
    AuthenticatedRecruteurOffresRouteChildren,
  )

interface AuthenticatedRecruteurRouteChildren {
  AuthenticatedRecruteurCandidaturesRoute: typeof AuthenticatedRecruteurCandidaturesRoute
  AuthenticatedRecruteurCvthequeRoute: typeof AuthenticatedRecruteurCvthequeRoute
  AuthenticatedRecruteurEntrepriseRoute: typeof AuthenticatedRecruteurEntrepriseRoute
  AuthenticatedRecruteurFavorisRoute: typeof AuthenticatedRecruteurFavorisRoute
  AuthenticatedRecruteurMessagesRoute: typeof AuthenticatedRecruteurMessagesRoute
  AuthenticatedRecruteurOffresRoute: typeof AuthenticatedRecruteurOffresRouteWithChildren
  AuthenticatedRecruteurIndexRoute: typeof AuthenticatedRecruteurIndexRoute
}

const AuthenticatedRecruteurRouteChildren: AuthenticatedRecruteurRouteChildren =
  {
    AuthenticatedRecruteurCandidaturesRoute:
      AuthenticatedRecruteurCandidaturesRoute,
    AuthenticatedRecruteurCvthequeRoute: AuthenticatedRecruteurCvthequeRoute,
    AuthenticatedRecruteurEntrepriseRoute:
      AuthenticatedRecruteurEntrepriseRoute,
    AuthenticatedRecruteurFavorisRoute: AuthenticatedRecruteurFavorisRoute,
    AuthenticatedRecruteurMessagesRoute: AuthenticatedRecruteurMessagesRoute,
    AuthenticatedRecruteurOffresRoute:
      AuthenticatedRecruteurOffresRouteWithChildren,
    AuthenticatedRecruteurIndexRoute: AuthenticatedRecruteurIndexRoute,
  }

const AuthenticatedRecruteurRouteWithChildren =
  AuthenticatedRecruteurRoute._addFileChildren(
    AuthenticatedRecruteurRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCandidatRoute: typeof AuthenticatedCandidatRouteWithChildren
  AuthenticatedRecruteurRoute: typeof AuthenticatedRecruteurRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCandidatRoute: AuthenticatedCandidatRouteWithChildren,
  AuthenticatedRecruteurRoute: AuthenticatedRecruteurRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EntreprisesRouteChildren {
  EntreprisesCompanyIdRoute: typeof EntreprisesCompanyIdRoute
}

const EntreprisesRouteChildren: EntreprisesRouteChildren = {
  EntreprisesCompanyIdRoute: EntreprisesCompanyIdRoute,
}

const EntreprisesRouteWithChildren = EntreprisesRoute._addFileChildren(
  EntreprisesRouteChildren,
)

interface OffresRouteChildren {
  OffresOfferIdRoute: typeof OffresOfferIdRoute
}

const OffresRouteChildren: OffresRouteChildren = {
  OffresOfferIdRoute: OffresOfferIdRoute,
}

const OffresRouteWithChildren =
  OffresRoute._addFileChildren(OffresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AProposRoute: AProposRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  EntreprisesRoute: EntreprisesRouteWithChildren,
  FaqRoute: FaqRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  OffresRoute: OffresRouteWithChildren,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
